apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-angualar-deployment
  labels:
    app: app1-angualar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-angualar
  template:
    metadata:
      labels:
        app: app1-angualar
    spec:
      containers:
        - name: app1-angualar
          image: angualaracr.azurecr.io/app/angualaracr
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-angular-loadbalancer-service
  labels:
    app: app1-angualar
spec:
  type: LoadBalancer
  selector:
    app: app1-angualar
  ports:
    - port: 80
      targetPort: 80


